name: Run all tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-nodes@v2
        with:
          node-version: 18
      - run: npm ci
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npm run test
